# Keep Kotlinx Serialization classes
-keepattributes *Annotation*, InnerClasses, EnclosingMethod, Signature, Exceptions
-keep,allowobfuscation,allowshrinking class kotlinx.serialization.json.JsonObjectSerializer
-keep,allowobfuscation,allowshrinking class kotlinx.serialization.json.JsonArraySerializer
-keep,allowobfuscation,allowshrinking class kotlinx.serialization.json.JsonLiteralSerializer
-keep,allowobfuscation,allowshrinking class kotlinx.serialization.json.JsonNullSerializer

# Keep DTO classes for correct serialization/deserialization
-keep class uz.coder.foottopbusiness.data.network.dto.** { *; }

# Also keep Serializers generated by Kotlinx Serialization
-keepclassmembers class uz.coder.foottopbusiness.data.network.dto.** {
    *** Companion;
    *** serializer(...);
}
